# short paths == fewer problems

# criterion does not support 32-bit on Windows
# TODO disable benchmarking to test on 32-bit
platform: x64

clone_folder: "c:\\pkg"
environment:
  global:
    BUILD: "stack"
    RESOLVER: "lts-6"
    GHC_OPTIONS: "-O0 -Werror"
    LANG: "en_US"
    LC_ALL: "C.UTF-8"

    STACK_ROOT: "c:\\sr"
    LOCAL_BIN: "%APPDATA%\\local\\bin"
    PATH: "%PATH%;%APPDATA%\\local\\bin"
    CABAL_REINIT_CONFIG: "y"
    TEST_INSTALL: "y"
    PACKAGE_TEST_VER: "1e80f64050c54541de3738de9449d8e0007e0198"

cache:
  - "%STACK_ROOT%" # stack root
  # ghc & msys - cache restore take almost same time as reinstall
  # - "%LOCALAPPDATA%\\Programs\\stack"
  - "%LOCAL_BIN%"
  - "%APPDATA%\\cabal"
  - "%APPDATA%\\ghc"

build: off

before_test:
- if not exist %LOCAL_BIN% mkdir %LOCAL_BIN%
- where stack.exe || curl -sSkL -ostack.zip https://github.com/commercialhaskell/stack/releases/download/v1.2.0/stack-1.2.0-windows-x86_64.zip && 7z x stack.zip stack.exe && move stack.exe %LOCAL_BIN%
- curl -sSkL -opackage-test.sh https://raw.githubusercontent.com/harendra-kumar/package-test/%PACKAGE_TEST_VER%/package-test.sh

test_script:
- stack setup > nul
- stack exec bash package-test.sh
